# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IsochronesDialog
                                 A QGIS plugin
 Isochrones
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-03
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Isochrones
        email                : Isochrones
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsMapLayerProxyModel
from qgis.gui import QgsMapLayerComboBox

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Isochrones_dialog_base.ui'))

class IsochronesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(IsochronesDialog, self).__init__(parent)
        self.setupUi(self)
        self._configure_widgets()
        self._connect_signals()
        self._setup_task_tabs()
    
    def _configure_widgets(self):
        self._configure_layer_combo(self.stopLayerCombo, QgsMapLayerProxyModel.PointLayer)
        self._configure_layer_combo(self.networkCombo, QgsMapLayerProxyModel.LineLayer)
        self._configure_layer_combo(self.populationCombo, QgsMapLayerProxyModel.PointLayer | QgsMapLayerProxyModel.PolygonLayer)
        
        self._configure_layer_combo(self.startPointLayerCombo, QgsMapLayerProxyModel.PointLayer | QgsMapLayerProxyModel.PolygonLayer)
        self._configure_layer_combo(self.networkComboTask2, QgsMapLayerProxyModel.LineLayer)
        self._configure_layer_combo(self.populationComboTask2, QgsMapLayerProxyModel.PointLayer | QgsMapLayerProxyModel.PolygonLayer)
        
        self.heightCombo.setFilters(QgsMapLayerProxyModel.RasterLayer | QgsMapLayerProxyModel.LineLayer | QgsMapLayerProxyModel.PolygonLayer)
        self.heightComboTask2.setFilters(QgsMapLayerProxyModel.RasterLayer | QgsMapLayerProxyModel.LineLayer | QgsMapLayerProxyModel.PolygonLayer)
        
        self.stopLayerCombo.layerChanged.connect(self.populate_stop_field_combo)
        self.populationCombo.layerChanged.connect(self.populate_population_field_combo)
        
        self.startPointLayerCombo.layerChanged.connect(self.populate_start_point_field_combo)
        self.populationComboTask2.layerChanged.connect(self.populate_population_field_combo_task2)
        self.networkComboTask2.layerChanged.connect(self.populate_uds_speed_field_combo)
        
        self.populate_stop_field_combo()
        self.populate_population_field_combo()
        self.populate_start_point_field_combo()
        self.populate_population_field_combo_task2()
        self.populate_uds_speed_field_combo()
    
    def _configure_layer_combo(self, combo: QgsMapLayerComboBox, filters):
        combo.setFilters(filters)
    
    def _setup_task_tabs(self):
        self.tabWidget.currentChanged.connect(self._on_tab_changed)
        self._on_tab_changed(0)
    
    def _on_tab_changed(self, index):
        if index == 0:
            self._show_task1_elements()
        elif index == 1:
            self._show_task2_elements()
    
    def _show_task1_elements(self):
        pass
    
    def _show_task2_elements(self):
        pass
    
    def _connect_signals(self):
        self.timeCustomCheck.toggled.connect(self.timeCustomSpin.setEnabled)
        self.useUdsSpeedsCheck.toggled.connect(self._on_uds_speed_toggled)
        self.transportCombo.currentTextChanged.connect(self._on_transport_changed)
    
    def populate_stop_field_combo(self):
        self.stopFieldCombo.clear()
        layer = self.stopLayerCombo.currentLayer()
        if not layer or layer.fields().isEmpty():
            return
        for field in layer.fields():
            if field.isNumeric() or field.typeName().lower() in ('string', 'text', 'varchar'):
                self.stopFieldCombo.addItem(field.name())
    
    def populate_population_field_combo(self):
        self.populationFieldCombo.clear()
        layer = self.populationCombo.currentLayer()
        if not layer or layer.fields().isEmpty():
            return
        numeric = [f for f in layer.fields() if f.isNumeric()]
        for field in numeric:
            self.populationFieldCombo.addItem(field.name())
    
    def populate_start_point_field_combo(self):
        self.startPointFieldCombo.clear()
        layer = self.startPointLayerCombo.currentLayer()
        if not layer or layer.fields().isEmpty():
            return
        for field in layer.fields():
            if field.isNumeric() or field.typeName().lower() in ('string', 'text', 'varchar'):
                self.startPointFieldCombo.addItem(field.name())
    
    def populate_population_field_combo_task2(self):
        self.populationFieldComboTask2.clear()
        layer = self.populationComboTask2.currentLayer()
        if not layer or layer.fields().isEmpty():
            return
        numeric = [f for f in layer.fields() if f.isNumeric()]
        for field in numeric:
            self.populationFieldComboTask2.addItem(field.name())
    
    def populate_uds_speed_field_combo(self):
        self.udsSpeedFieldCombo.clear()
        layer = self.networkComboTask2.currentLayer()
        if not layer or layer.fields().isEmpty():
            return
        numeric = [f for f in layer.fields() if f.isNumeric()]
        for field in numeric:
            self.udsSpeedFieldCombo.addItem(field.name())
        self.udsSpeedFieldCombo.addItem("")
    
    def _on_uds_speed_toggled(self, checked):
        self.speedSpinTask2.setEnabled(not checked)
        self.labelSpeedTask2.setEnabled(not checked)
        self.udsSpeedFieldCombo.setEnabled(checked)
        self.labelUdsSpeedField.setEnabled(checked)
    
    def _on_transport_changed(self, transport):
        default_speeds = {
            'Пешком': 5.0,
            'Велосипед': 14.0,
            'Автомобиль': 50.0,
            'Такси': 50.0
        }
        if transport in default_speeds:
            self.speedSpinTask2.setValue(default_speeds[transport])